%% Alumno: Néstor Rodríguez Vico. 75573052C. nrv23@correo.ugr.es

%% Ejercicio 2
%{
Coge una imagen en color y utiliza imadjust o histeq para mejorar el 
contraste. Considera estas posibilidades:
    2.1: Ecualizar por separado cada banda R, G, B.
    2.2: Ecualizar por separado cada banda H, S, V.

¿Cómo podemos conseguir un buen ecualizado para imágenes en color? Usa 
danza.ppm para contestar a esta pregunta.
%}

I_RGB=imread('p3_imagenes/danza.ppm');
figure, subplot(2, 3, 1); imshow(I_RGB(:,:,1)), title('Orig Rojo');
    subplot(2, 3, 2); imshow(I_RGB(:,:,2)), title('Orig Verde');
    subplot(2, 3, 3); imshow(I_RGB(:,:,2)), title('Orig Azul');
    subplot(2, 3, 4); imhist(I_RGB(:,:,1)), title('Orig Hist Rojo');
    subplot(2, 3, 5); imhist(I_RGB(:,:,2)), title('Orig Hist Verde');
    subplot(2, 3, 6); imhist(I_RGB(:,:,2)), title('Orig Hist Azul');
    
% 2.1
equ_rgb = cat(3, histeq(I_RGB(:,:,1)), histeq(I_RGB(:,:,2)), ...
    histeq(I_RGB(:,:,3)));

figure, subplot(2, 3, 1); imshow(equ_rgb(:,:,1)), ...
    title('Ecualizada Rojo'), ...
    subplot(2, 3, 2); imshow(equ_rgb(:,:,2)), ...
    title('Ecualizada Verde'), ...
    subplot(2, 3, 3); imshow(equ_rgb(:,:,2)), ...
    title('Ecualizada Azul'), ...
    subplot(2, 3, 4); imhist(equ_rgb(:,:,1)), ...
    title('Ecualizada Hist Rojo'), ...
    subplot(2, 3, 5); imhist(equ_rgb(:,:,2)), ...
    title('Ecualizada Hist Verde'), ...
    subplot(2, 3, 6); imhist(equ_rgb(:,:,2)), ...
    title('Ecualizada Hist Azul');

% 2.2
I_HSV = rgb2hsv(I_RGB);
equ_hsv = hsv2rgb(cat(3, histeq(I_HSV(:,:,1)), histeq(I_HSV(:,:,2)), ...
    histeq(I_HSV(:,:,3))));

figure, subplot(2, 3, 1); imshow(equ_hsv(:,:,1)), title('H'), ...
    subplot(2, 3, 2); imshow(equ_hsv(:,:,2)), title('S'), ...
    subplot(2, 3, 3); imshow(equ_hsv(:,:,2)), title('V'), ...
    subplot(2, 3, 4); imhist(equ_hsv(:,:,1)), title('Hist H'), ...
    subplot(2, 3, 5); imhist(equ_hsv(:,:,2)), title('Hist S'), ...
    subplot(2, 3, 6); imhist(equ_hsv(:,:,3)), title('Hist V');

% 2.3
figure, subplot(1, 3, 1); imshow(I_RGB), title('Original'), ...
    subplot(1, 3, 2); imshow(equ_rgb), title('equ rgb'), ...
    subplot(1, 3, 3); imshow(equ_hsv), title('equ hsv');