%% Alumno: Néstor Rodríguez Vico. 75573052C. nrv23@correo.ugr.es

%% Ejercicio 1
%{
Compara el resultado que producen el filtrado gaussiano y el filtro de 
mediana sobre las imágenes disney_r1.png ... disney_r5.png.
%}

dr1 = imread('p4_imagenes/disney_r1.png');
dr2 = imread('p4_imagenes/disney_r2.png');
dr3 = imread('p4_imagenes/disney_r3.png');
dr4 = imread('p4_imagenes/disney_r4.png');
dr5 = imread('p4_imagenes/disney_r5.png');

gauss = fspecial('gaussian',[15 15], 10);

figure, subplot(3,5,1), imshow(dr1), title('dr1'), ...
    subplot(3,5,2), imshow(dr2), title('dr2'), ...
    subplot(3,5,3), imshow(dr3), title('dr3'), ...
    subplot(3,5,4), imshow(dr4), title('dr4'), ...
    subplot(3,5,5), imshow(dr5), title('dr5'), ...
    subplot(3,5,6), imshow(imfilter(dr1, gauss)), title('gauss dr1'), ...
    subplot(3,5,7), imshow(imfilter(dr2, gauss)), title('gauss dr2'), ...
    subplot(3,5,8), imshow(imfilter(dr3, gauss)), title('gauss dr3'), ...
    subplot(3,5,9), imshow(imfilter(dr4, gauss)), title('gauss dr4'), ...
    subplot(3,5,10), imshow(imfilter(dr5, gauss)), title('gauss dr5'), ...
    subplot(3,5,11), imshow(medfilt2(dr1,[10 10])), ...
        title('median dr1'), ...
    subplot(3,5,12), imshow(medfilt2(dr2,[10 10])), ...
        title('median dr2'), ...
    subplot(3,5,13), imshow(medfilt2(dr3,[10 10])), ...
        title('median dr3'), ...
    subplot(3,5,14), imshow(medfilt2(dr4,[10 10])), ...
        title('median dr4'), ...
    subplot(3,5,15), imshow(medfilt2(dr5,[10 10])), ...
        title('median dr5');
    
%{
Podemos ver que el filtro Gaussiano hace todas las imágenes muy borrosas,
independientemente de la cantidad de ruido que tengan. Sin embargo, el
filtro mediana se comporta bastante bien en imágenes que no tienen un ruido
muy marcado (disney_r1, disney_r2 y disney_r4) pero también en imágenes con
bastante ruido (disney_r3 y disney_r5).
%}